const TOUR_CONFIG = {
    tours: [
      "Spice Tour",
      "Historical City Tour",
      "Prison Island Boat Trip",
      "Jozani Forest Tour",
      "Dolphin Tour",
      "Sunset & The Rock Restaurant",
      "Snorkeling",
      "Village Tour",
      "Motorbike Renting",
      "Mnemba Snorkeling & Trip to the North",
      "Safari Blue",
      "Local Game Fishing",
      "Swimming in the Cave",
      "Sailing into the Sunset",
      "Quad Tour",
    ],
    locations: [
      "Stone Town",
      "Nungwi",
      "Kendwa",
      "Matemwe",
      "Pongwe",
      "Kiwengwa",
      "Uroa",
      "Chwaka",
      "Michamvi",
      "Bwejuu",
      "Pingwe",
      "Kizimkazi",
      "Fumba",
      "Paje",
      "Jambiani",
      "Makunduchi",
    ],
    images: [
      "/gallery/1.jpg",
      "/gallery/2.jpg",
      "/gallery/3.jpg",
      "/gallery/4.jpg",
      "/gallery/5.jpg",
      "/gallery/6.jpg",
    ],
  };
  
  export default TOUR_CONFIG;